### ISSUE TITLE
Troubles running DeepDicomSort on BIGR GPU Cluster

### ISSUE THREAD

**Issue by Sikerdebaard** [ErasmusMC-NeuroOnco/DeepDicomSort#10]
Hi Sebastian,

I'm running into some issues with DeepDicomSort on the BIGR GPU Cluster.
The manual states that fsl 5.x is necessary, but this is unavailable on the cluster. Because of this I've attempted to run the code with fsl 6.0.4. It looks like this version is incompatible. Any ideas how to get this working on the GPU Cluster?

```bash
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 127: /bin/fslswapdim: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 95: /bin/remove_ext: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 97: /bin/tmpnam: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 99: /bin/imtest: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 99: [: =: unary operator expected
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 104: /bin/fslval: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 105: /bin/fslval: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 106: [: too many arguments
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 115: [: =: unary operator expected
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 118: /bin/fslhd: No such file or directory
/trinity/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std: line 119: /bin/avscale: No such file or directory
(standard_in) 1: syntax error
```

**Comment by Svdvoort** [comment]
You can try to use the latest SimpleITK and use the [`DICOMOrient` filter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DICOMOrientImageFilter.html).

It should (theoretically) do the same as `fslreorient2std`, but no guarantees of course regarding the results.

`fslreorient2std` is only used because I had images that did not adhere to the 'standard' orientation, and thus when creating slices sometimes the slices were taken for example coronal instead of axial. If you are sure that all your images have the same orientation (or you can all give them the same orientation in some other way), you don't need the `fslreorient2std` step.

**Comment by Sikerdebaard** [comment]
Turns out the module was loaded incorrectly on the cluster. After reloading it worked out of the box! Thanks!

**Comment by hajerkr** [comment]
Hey @Sikerdebaard , I'm also trying to run this from the uni cluster, but I am having trouble setting the right paths for the dcm2niix and fsl bin directories. For fsl for instance, this is what I see in the /apps/modules/modulefiles/fsl/6.0.1 file 
![image](https://user-images.githubusercontent.com/13291010/162614316-82b7abf9-6433-43db-8d6e-91c59ba1a2e2.png)

I hope you can help? Thanks (:
